# Question 2:

In experiments, Dendrites select a unique radius of curvature $R_{tip}$ and growth velocity $v_{tip}$ for a specific undercooling $\Delta T$. The Lipton-Glicksman-Kurz (LGK) model is an approximate solution for $(R_{tip},v_{tip})$ based on the marginal stability theory.

The $R_{tip}$ and $v_{tip}$ can be found by solving the following equations:

$$\Delta T = \frac{2\Gamma_{sl}}{R_{tip}} - m_l C_0 \frac{(1-k) Iv_{3D}(Pe_C)}{1-(1-k) Iv_{3D}(Pe_C)}$$

$$R_{tip}^2 v = -\bigg( \frac{1}{\sigma^{*}} \bigg)^2 \frac{2D_l \Gamma_{sl}}{m C_0 (1-k)}$$

Where $Iv_{3D}$ is the Ivantsov function given by

$$Iv_{3D}(x) = x E_1(x) e^{x}$$

$E_1$ is the exponential integral

$$E_1(x) = \int_x^\infty \frac{e^{-y}}{y} dy$$


#### Peclet numbers:

Pe_C is soultal peclet number

$$Pe_C = \frac{R_{tip}v^{*}}{2D}$$

In [1]:
# import reqired libraries

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import exp1
from scipy.optimize import fsolve

% matplotlib inline

In [21]:
# Define stuff

# From values for Nickel



# For X_Cu = 0.1

C_0 = 0.2     
k = 0.1
m = -200         # Liquidus slope  K
D = 3e-09            # Solute Diffusivity m^2/s
T_a = 800       # Melting Point K
sig = 0.1           # Surface energy J/m^2

Gam = sig/(8.314/1e-5*np.log(C_0)*C_0*(k-1))    # Gibbs-Thomson Parameter


# Ivantsov function

def I3(P):
    
    return P*exp1(P)*np.exp(P)

# Peclet numbers

def P_c(R,v):
    
    return R*v/(2*D)

# define functions to optimize

def fun1(R,v,delT):
    
    #t_t = L_f/C_p*I3(P_t(R,v))
    t_c = -m*C_0*(1-k)*I3(P_c(R,v))/(1 - (1-k)*I3(P_c(R,v)))
    t_r = 2*Gam/R
    
    return delT - (t_c + t_r)
/
def fun2(R,v,sigma):
    
    return R*R*v + Gam*2*D/(sigma*sigma*m*C_0*(1-k))

print(Gam)

4.1518652243846516e-07


In [48]:
def funs(v_n,R_n):
    return fun1(R_n,v_n,5)

Rs = np.array([1e-6,3e-6,5e-6,1e-5,8e-6])
vs = np.array([fsolve(funs,1e-4,R) for R in Rs])[:,0]
print(Rs,vs)
np.multiply(Rs,vs)

[1.e-06 3.e-06 5.e-06 1.e-05 8.e-06] [2.19147400e-04 8.61069801e-05 5.32729592e-05 2.72442234e-05
 3.38649146e-05]


array([2.19147400e-10, 2.58320940e-10, 2.66364796e-10, 2.72442234e-10,
       2.70919316e-10])

### $R_{tip}$ and $v_{tip}$ as functions of undercooling:

In [55]:
def opt_fn(x,delT,sigma):
    
    R = x[0]
    v = x[1]
    
    return fun1(R,v,delT),fun2(R,v,sigma)

fsolve(opt_fn,[1e-7,1e-3],args=(5,0.025))

array([4.13277306e-07, 3.43548671e-04])

In [56]:
l1 = np.power(32*D*Gam*360/np.power(0.025,2), 0.25)/(np.power(1e5,0.5)*np.power(2e-6,0.25))
print(l1)

0.0010350867326731027
